version: '3'

output: 'prefixed'

tasks:

  deploy:
    cmds:
      - >
        docker buildx create
        --name builder-multi-platform
        --bootstrap
        --use
      - >
        docker buildx build
        --platform linux/amd64,linux/arm64
        --tag alexandersidorov/iteen-python:latest
        --push
        ./src/
    desc: build all platforms and push to Docker Hub
    dir: "{{.ROOT_DIR}}"
    interactive: true
    preconditions:
      - docker info
    run: once
